vim.api.nvim_set_hl(0, "rainbowcol1", { fg = "#f1c40f" })
vim.api.nvim_set_hl(0, "rainbowcol2", { fg = "#1abc9c" })
vim.api.nvim_set_hl(0, "rainbowcol3", { fg = "#3498db" })
vim.api.nvim_set_hl(0, "rainbowcol4", { fg = "#ef5777" })
vim.api.nvim_set_hl(0, "rainbowcol5", { fg = "#05c46b" })
vim.api.nvim_set_hl(0, "rainbowcol6", { fg = "#0fbcf9" })
vim.api.nvim_set_hl(0, "rainbowcol7", { fg = "#e67e22" })
vim.api.nvim_set_hl(0, "Normal", { fg = "#a6accd", bg = "#0d1117" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#27ae60", italic = true })
vim.api.nvim_set_hl(0, "Constant", { fg = "#dcdcaa" })
vim.api.nvim_set_hl(0, "String", { fg = "#c3e88d" })
vim.api.nvim_set_hl(0, "Character", { fg = "#ce9178" })
vim.api.nvim_set_hl(0, "Number", { fg = "#f78c6c" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#ff9cac" })
vim.api.nvim_set_hl(0, "Float", { fg = "#b5cea8" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "Function", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#89ddff", italic = true })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "Label", { fg = "#9cdcfe" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "Exception", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "Include", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "Define", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "Title", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "PreCondit", { fg = "#9cdcfe" })
vim.api.nvim_set_hl(0, "Type", { fg = "#9cdcfe" })
vim.api.nvim_set_hl(0, "StorageClass", { fg = "#9cdcfe" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#ffcb6b" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#ffcb6b" })
vim.api.nvim_set_hl(0, "Special", { fg = "#6695fa", italic = true })
vim.api.nvim_set_hl(0, "SpecialComment", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "Error", { fg = "#ff4747", bold = true, reverse = true })
vim.api.nvim_set_hl(0, "Todo", { fg = "#c586c0", bold = true, italic = true })
vim.api.nvim_set_hl(0, "Underlined", { fg = "#89ddff", underline = true })
vim.api.nvim_set_hl(0, "Cursor", { fg = "#515052", bg = "#aeafad" })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = "#2c323c" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#abb2bf", bold = true })
vim.api.nvim_set_hl(0, "SignColumn", { bg = "#0d1117" })
vim.api.nvim_set_hl(0, "Conceal", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#2c323c" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#2c323c" })
vim.api.nvim_set_hl(0, "Directory", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#1e1e1e", bg = "#27ae60" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "#dcdcaa", underline = true })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#1e1e1e", bg = "#d16969" })
vim.api.nvim_set_hl(0, "DiffText", { fg = "#1e1e1e", bg = "#dcdcaa" })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = "#f44747" })
vim.api.nvim_set_hl(0, "VertSplit", { fg = "#3e4452" })
vim.api.nvim_set_hl(0, "Folded", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "FoldColumn", {  })
vim.api.nvim_set_hl(0, "IncSearch", { bg = "#5c6370" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#858585" })
vim.api.nvim_set_hl(0, "NonText", { fg = "#3b4048" })
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#abb2bf", bg = "#282c34" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#1e1e1e", bg = "#6695fa" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#3b4048" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#abb2bf" })
vim.api.nvim_set_hl(0, "Question", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "QuickFixLine", { bg = "#5c6370" })
vim.api.nvim_set_hl(0, "Search", { bg = "#5c6370" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#3b4048" })
vim.api.nvim_set_hl(0, "SpellBad", { fg = "#f44747", underline = true })
vim.api.nvim_set_hl(0, "SpellCap", { fg = "#d7ba7d" })
vim.api.nvim_set_hl(0, "SpellLocal", { fg = "#d7ba7d" })
vim.api.nvim_set_hl(0, "SpellRare", { fg = "#d7ba7d" })
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#abb2bf", bg = "#2c323c" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "StatusLineTerm", { fg = "#abb2bf", bg = "#2c323c" })
vim.api.nvim_set_hl(0, "StatusLineTermNC", { fg = "#2c323c" })
vim.api.nvim_set_hl(0, "TabLine", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "#252526" })
vim.api.nvim_set_hl(0, "Terminal", { fg = "#abb2bf", bg = "#1e1e1e" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#3e4452" })
vim.api.nvim_set_hl(0, "VisualNOS", { fg = "#3e4452" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#dcdcaa" })
vim.api.nvim_set_hl(0, "WildMenu", { fg = "#1e1e1e", bg = "#6695fa" })
vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = "#1e1e1e" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#27ae60" })
vim.api.nvim_set_hl(0, "TSError", { fg = "#f44747" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#abb2bf", bold = true })
vim.api.nvim_set_hl(0, "Special", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "Define", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "String", { fg = "#c3e88d" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#d7ba7d" })
vim.api.nvim_set_hl(0, "Character", { fg = "#c3e88d" })
vim.api.nvim_set_hl(0, "Number", { fg = "#f78c6c" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#ff9cac", bold = true, italic = true })
vim.api.nvim_set_hl(0, "Float", { fg = "#f78c6c" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "Include", { fg = "#ffcb6b" })
vim.api.nvim_set_hl(0, "Special", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#dcdcaa" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#a6accd" })
vim.api.nvim_set_hl(0, "Parameter", { fg = "#729cb3" })
vim.api.nvim_set_hl(0, "Function", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "htmlArg", { fg = "#c586c0", bold = true })
vim.api.nvim_set_hl(0, "htmlBold", { fg = "#d7ba7d", bold = true })
vim.api.nvim_set_hl(0, "htmlEndTag", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "htmlItalic", { fg = "#c586c0", italic = true })
vim.api.nvim_set_hl(0, "htmlLink", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "htmlSpecialChar", { fg = "#d7ba7d" })
vim.api.nvim_set_hl(0, "htmlSpecialTagName", { fg = "#f07178" })
vim.api.nvim_set_hl(0, "htmlTag", { fg = "#f07178" })
vim.api.nvim_set_hl(0, "htmlTagN", { fg = "#f07178" })
vim.api.nvim_set_hl(0, "htmlTagName", { fg = "#f07178" })
vim.api.nvim_set_hl(0, "htmlTitle", { fg = "#a6accd" })
vim.api.nvim_set_hl(0, "Type", { fg = "#ffcb6b" })
vim.api.nvim_set_hl(0, "@type", { fg = "#ffcb6b" })
vim.api.nvim_set_hl(0, "@constructor", { fg = "#ffcb6b" })
vim.api.nvim_set_hl(0, "@property", { fg = "#729cb3" })
vim.api.nvim_set_hl(0, "@property", { fg = "#729cb3" })
vim.api.nvim_set_hl(0, "@variable.member", { fg = "#729cb3" })
vim.api.nvim_set_hl(0, "@keyword.conditional", { fg = "#89ddff", italic = true })
vim.api.nvim_set_hl(0, "@punctuation.special", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "@keyword.import", { fg = "#89ddff", bold = true, italic = true })
vim.api.nvim_set_hl(0, "@variable.builtin", { fg = "#05c46b", bold = true, italic = true })
vim.api.nvim_set_hl(0, "@constant.builtin", { fg = "#89ddff", bold = true, italic = true })
vim.api.nvim_set_hl(0, "@tag.delimiter", { fg = "#89ddff", italic = true })
vim.api.nvim_set_hl(0, "@keyword.operator", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "@keyword.return", { fg = "#89ddff", italic = true })
vim.api.nvim_set_hl(0, "@keyword.repeat", { fg = "#89ddff", italic = true })
vim.api.nvim_set_hl(0, "@tag", { fg = "#f07178" })
vim.api.nvim_set_hl(0, "@tag.attribute", { fg = "#c586c0", bold = true })
vim.api.nvim_set_hl(0, "@tag.builtin", { fg = "#ffcb6b" })
vim.api.nvim_set_hl(0, "@type.qualifier", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "@lsp.type.function", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "@type.builtin", { fg = "#ffcb6b" })
vim.api.nvim_set_hl(0, "@variable", { fg = "#a6accd" })
vim.api.nvim_set_hl(0, "@module", { fg = "#dcdcaa", italic = true })
vim.api.nvim_set_hl(0, "@function.macro", { fg = "#dcdcaa" })
vim.api.nvim_set_hl(0, "@attribute.builtin", { fg = "#05c46b", italic = true })
vim.api.nvim_set_hl(0, "@markup.heading.1", { fg = "#fca608" })
vim.api.nvim_set_hl(0, "@markup.heading.2", { fg = "#fc7005" })
vim.api.nvim_set_hl(0, "@markup.heading.3", { fg = "#fce305" })
vim.api.nvim_set_hl(0, "@markup.heading.4", { fg = "#fc4f05" })
vim.api.nvim_set_hl(0, "@markup.heading.5", { fg = "#d7fc05" })
vim.api.nvim_set_hl(0, "@markup.heading.6", { fg = "#ffcb6b" })
vim.api.nvim_set_hl(0, "@markup.link.label", { fg = "#f07178" })
vim.api.nvim_set_hl(0, "@markup.link.url", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "@markup.raw", {  })
vim.api.nvim_set_hl(0, "@_label", {  })
vim.api.nvim_set_hl(0, "@_label.markdown_inline", {  })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#89ddff", italic = true })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#89ddff", italic = true })
vim.api.nvim_set_hl(0, "Label", { fg = "#9cdcfe" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#89ddff", italic = true })
vim.api.nvim_set_hl(0, "Operator", { fg = "#89ddff", bold = true })
vim.api.nvim_set_hl(0, "Exception", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#ff00ff" })
vim.api.nvim_set_hl(0, "Include", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "Variable", { fg = "#a6accd" })
vim.api.nvim_set_hl(0, "TSNone", { fg = "#a6accd" })
vim.api.nvim_set_hl(0, "TSStrong", { fg = "#ffff00" })
vim.api.nvim_set_hl(0, "TSEmphasis", { fg = "#ffff00" })
vim.api.nvim_set_hl(0, "TSUnderline", { fg = "#ffff00" })
vim.api.nvim_set_hl(0, "Title", { fg = "#a6accd" })
vim.api.nvim_set_hl(0, "Underlined", { underline = true })
vim.api.nvim_set_hl(0, "Label", { fg = "#f07178" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "TSQueryLinterError", { fg = "#ff8800" })
vim.api.nvim_set_hl(0, "markdownBlockquote", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "markdownBold", { fg = "#d7ba7d", bold = true })
vim.api.nvim_set_hl(0, "markdownCode", { fg = "#27ae60" })
vim.api.nvim_set_hl(0, "markdownCodeBlock", { fg = "#27ae60" })
vim.api.nvim_set_hl(0, "markdownCodeDelimiter", { fg = "#27ae60" })
vim.api.nvim_set_hl(0, "markdownH1", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "markdownH2", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "markdownH3", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "markdownH4", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "markdownH5", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "markdownH6", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "markdownHeadingDelimiter", { fg = "#d16969" })
vim.api.nvim_set_hl(0, "markdownHeadingRule", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "markdownId", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "markdownIdDeclaration", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "markdownIdDelimiter", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "markdownItalic", { fg = "#c586c0", italic = true })
vim.api.nvim_set_hl(0, "markdownLinkDelimiter", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "markdownLinkText", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "markdownListMarker", { fg = "#d16969" })
vim.api.nvim_set_hl(0, "markdownOrderedListMarker", { fg = "#d16969" })
vim.api.nvim_set_hl(0, "markdownRule", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "markdownUrl", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "CocExplorerIndentLine", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "CocExplorerBufferRoot", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "CocExplorerFileRoot", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "CocExplorerBufferFullPath", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "CocExplorerFileFullPath", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "CocExplorerBufferReadonly", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "CocExplorerBufferModified", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "CocExplorerBufferNameVisible", { fg = "#ce9178" })
vim.api.nvim_set_hl(0, "CocExplorerFileReadonly", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "CocExplorerFileModified", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "CocExplorerFileHidden", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "CocExplorerHelpLine", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "EasyMotionTarget", { fg = "#f44747", bold = true })
vim.api.nvim_set_hl(0, "EasyMotionTarget2First", { fg = "#f44747", bold = true })
vim.api.nvim_set_hl(0, "EasyMotionTarget2Second", { fg = "#f44747", bold = true })
vim.api.nvim_set_hl(0, "EasyMotionShade", {  })
vim.api.nvim_set_hl(0, "StartifyNumber", { fg = "#b5cea8" })
vim.api.nvim_set_hl(0, "StartifySelect", { fg = "#27ae60" })
vim.api.nvim_set_hl(0, "StartifyBracket", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "StartifySpecial", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "StartifyVar", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "StartifyPath", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "StartifyFile", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "StartifySlash", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "StartifyHeader", { fg = "#9cdcfe" })
vim.api.nvim_set_hl(0, "StartifySection", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "StartifyFooter", { fg = "#27ae60" })
vim.api.nvim_set_hl(0, "WhichKey", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "WhichKeySeperator", { fg = "#27ae60" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = "#4fc1ff" })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "diffAdded", { fg = "#27ae60" })
vim.api.nvim_set_hl(0, "diffRemoved", { fg = "#d16969" })
vim.api.nvim_set_hl(0, "diffFileId", { fg = "#6695fa", bold = true, reverse = true })
vim.api.nvim_set_hl(0, "diffFile", { fg = "#3b4048" })
vim.api.nvim_set_hl(0, "diffNewFile", { fg = "#27ae60" })
vim.api.nvim_set_hl(0, "diffOldFile", { fg = "#d16969" })
vim.api.nvim_set_hl(0, "debugPc", { bg = "#89ddff" })
vim.api.nvim_set_hl(0, "debugBreakpoint", { fg = "#d16969", reverse = true })
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#23d18b" })
vim.api.nvim_set_hl(0, "GitSignsAddNr", { fg = "#23d18b" })
vim.api.nvim_set_hl(0, "GitSignsAddLn", { fg = "#23d18b" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#0c7d9d" })
vim.api.nvim_set_hl(0, "GitSignsChangeNr", { fg = "#0c7d9d" })
vim.api.nvim_set_hl(0, "GitSignsChangeLn", { fg = "#0c7d9d" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#94151b" })
vim.api.nvim_set_hl(0, "GitSignsDeleteNr", { fg = "#94151b" })
vim.api.nvim_set_hl(0, "GitSignsDeleteLn", { fg = "#94151b" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { fg = "#f44747" })
vim.api.nvim_set_hl(0, "DiagnosticFloatingError", { fg = "#f44747" })
vim.api.nvim_set_hl(0, "DiagnosticSignError", { fg = "#f44747" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { fg = "#f44747" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { fg = "#ff8800" })
vim.api.nvim_set_hl(0, "DiagnosticFloatingWarn", { fg = "#ff8800" })
vim.api.nvim_set_hl(0, "DiagnosticSignWarn", { fg = "#ff8800" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { fg = "#ff8800" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { fg = "#4fc1ff" })
vim.api.nvim_set_hl(0, "DiagnosticFloatingInfo", { fg = "#4fc1ff" })
vim.api.nvim_set_hl(0, "DiagnosticSignInfo", { fg = "#4fc1ff" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { fg = "#4fc1ff" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { fg = "#729cb3" })
vim.api.nvim_set_hl(0, "DiagnosticFloatingHint", { fg = "#729cb3" })
vim.api.nvim_set_hl(0, "DiagnosticSignHint", { fg = "#729cb3" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { fg = "#729cb3" })
vim.api.nvim_set_hl(0, "QuickScopePrimary", { fg = "#00c7df", underline = true })
vim.api.nvim_set_hl(0, "QuickScopeSecondary", { fg = "#ef5f70", underline = true })
vim.api.nvim_set_hl(0, "MatchWord", { underline = true })
vim.api.nvim_set_hl(0, "MatchParen", { underline = true })
vim.api.nvim_set_hl(0, "MatchWordCur", { underline = true })
vim.api.nvim_set_hl(0, "MatchParenCur", { underline = true })
vim.api.nvim_set_hl(0, "NvimTreeImageFile", { fg = "#c586c0" })
vim.api.nvim_set_hl(0, "NvimTreeGitDirty", { fg = "#81b88b" })
vim.api.nvim_set_hl(0, "NvimTreeGitDeleted", { fg = "#81b88b" })
vim.api.nvim_set_hl(0, "NvimTreeGitStaged", { fg = "#81b88b" })
vim.api.nvim_set_hl(0, "NvimTreeGitMerge", { fg = "#81b88b" })
vim.api.nvim_set_hl(0, "NvimTreeGitRenamed", { fg = "#81b88b" })
vim.api.nvim_set_hl(0, "NvimTreeGitNew", { fg = "#81b88b" })
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "NvimTreeSymlink", { fg = "#29b8d8" })
vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", { fg = "#6695fa" })
vim.api.nvim_set_hl(0, "NvimTreeRootFolder", { fg = "#a6accd", bold = true })
vim.api.nvim_set_hl(0, "NvimTreeExecFile", { fg = "#23d18b" })
vim.api.nvim_set_hl(0, "NvimTreeSpecialFile", { fg = "#ffcc66" })
vim.api.nvim_set_hl(0, "BufferCurrent", { fg = "#6695fa", bg = "#0d1117" })
vim.api.nvim_set_hl(0, "BufferCurrentIndex", { fg = "#6695fa", bg = "#0d1117" })
vim.api.nvim_set_hl(0, "BufferCurrentMod", { fg = "#6695fa", bg = "#0d1117" })
vim.api.nvim_set_hl(0, "BufferCurrentSign", { fg = "#6695fa", bg = "#0d1117" })
vim.api.nvim_set_hl(0, "BufferCurrentTarget", { fg = "#d16969", bg = "#0d1117", bold = true })
vim.api.nvim_set_hl(0, "BufferVisible", { fg = "#a6accd", bg = "#0d1117" })
vim.api.nvim_set_hl(0, "BufferVisibleIndex", { fg = "#a6accd", bg = "#0d1117" })
vim.api.nvim_set_hl(0, "BufferVisibleMod", { fg = "#a6accd", bg = "#0d1117" })
vim.api.nvim_set_hl(0, "BufferVisibleSign", { fg = "#a6accd", bg = "#0d1117" })
vim.api.nvim_set_hl(0, "BufferVisibleTarget", { fg = "#d16969", bg = "#0d1117", bold = true })
vim.api.nvim_set_hl(0, "BufferInactive", { fg = "#858585", bg = "#2e2e2e" })
vim.api.nvim_set_hl(0, "BufferInactiveIndex", { fg = "#858585", bg = "#2e2e2e" })
vim.api.nvim_set_hl(0, "BufferInactiveMod", { fg = "#858585", bg = "#2e2e2e" })
vim.api.nvim_set_hl(0, "BufferInactiveSign", { fg = "#858585", bg = "#2e2e2e" })
vim.api.nvim_set_hl(0, "BufferInactiveTarget", { fg = "#d16969", bg = "#2e2e2e", bold = true })
vim.api.nvim_set_hl(0, "CodiVirtualText", { fg = "#6395ec" })
vim.api.nvim_set_hl(0, "IndentBlanklineContextChar", { fg = "#707070" })
vim.api.nvim_set_hl(0, "VimwikiHeader1", { fg = "#ce9178", bold = true })
vim.api.nvim_set_hl(0, "VimwikiHeader2", { fg = "#27ae60", bold = true })
vim.api.nvim_set_hl(0, "VimwikiHeader3", { fg = "#6695fa", bold = true })
vim.api.nvim_set_hl(0, "VimwikiHeader4", { fg = "#89ddff", bold = true })
vim.api.nvim_set_hl(0, "VimwikiHeader5", { fg = "#d7ba7d", bold = true })
vim.api.nvim_set_hl(0, "VimwikiHeader6", { fg = "#c586c0", bold = true })
vim.api.nvim_set_hl(0, "VimwikiLink", { fg = "#4fc1ff" })
vim.api.nvim_set_hl(0, "VimwikiHeaderChar", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "VimwikiHR", { fg = "#dcdcaa" })
vim.api.nvim_set_hl(0, "VimwikiList", { fg = "#ce9178" })
vim.api.nvim_set_hl(0, "VimwikiTag", { fg = "#ce9178" })
vim.api.nvim_set_hl(0, "VimwikiMarkers", { fg = "#5c6370" })
